### ISSUE TITLE
create recipe models

### ISSUE THREAD

**Issue by JayB-Kayode** [lcabrini/in-my-fridge#4]
since we are working with recipes let's create a recipes models with 
name , Date , Description

**Comment by lcabrini** [comment]
That is fine. But we would need to set up an app for recipes first. Can we just call it recipes?

**Comment by JayB-Kayode** [comment]
oki let's keep that name for app recipes or we can also call it recipesApp ....

**Comment by lcabrini** [comment]
Hm.. I prefer recipes, if you don't mind. Let's keep it simple.

**Comment by JayB-Kayode** [comment]
+1

**Comment by JayB-Kayode** [comment]
let me then create the app recipes

**Comment by JayB-Kayode** [comment]
it looks like this issue is complete ! can i close it now ?

**Comment by lcabrini** [comment]
+1
